sif : 'datafiles/wags.sif'
ref : 'datafiles/goldenPath.Ec_build-3.0_wMSY.fa'
gtf : 'datafiles/Equus_caballus.EquCab3.0.105_sorted.gtf.gz'
updown : '1000'
VCF : 'joint_call.goldenPath.20230726.vcf.gz'
final : 'joint_call.goldenPath_annotated.20230726.vcf.gz'
snpEffdatabase : 'EquCab3.0.105'
